### GET FRIENDs
GET http://localhost:8080/friends

### GET FRIEND
GET http://localhost:8080/friends/niharika


### ADD A FRIEND
POST http://localhost:8080/addfriend
Content-Type: application/json

{
    "name": "niha",
    "status": "enemy"
}

### UPDATE STATUS OF A FRIEND
PATCH http://localhost:8080/changestatus
Content-Type: application/json

{
    "name": "honey",
    "newStatus": "friend"
}


###DELETE A FRIEND
DELETE http://localhost:8080/friends
Content-Type: application/json

{
    "name": "honey"
}


